### ISSUE TITLE
Use two space indent or four space/tab indent?

### ISSUE THREAD

**Issue by exfret** [maxsu/balancers2#10]
Kyle (me) has been using four. Max has been using two. We should standardize this at some point.

**Comment by maxsu** [comment]
I've been using the [google c++ standard](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs). I auto-format with [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) using the `Google` style.

I propose that we standardize around the google standards, and make sure that we format code with clang-format before committing.

**Comment by exfret** [comment]
Okay, I will try to stick to two spaces. I guess it doesn't matter since clang formatter will do it for me, but it's easy to switch my editors.

**Comment by maxsu** [comment]
@exfret we have a new formatting script, `tidy.sh`, as of commit 27b26f68ba886cba1f388125f615ba7b7ebadbaa

Check it out! It converts everything to 2 space indent.
